# Generated by Django 4.2.1 on 2023-05-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year_class',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
